### ISSUE TITLE
Rule execution fails when trying to run expressions

### ISSUE THREAD

**Issue by PulThom** [jdereg/n-cube#458]
We were exploring some features of nCube in search of a Rule Engine for our project and was successful in setting up a very limited demo version using Axis type as SET,DISCRETE etc. 

But, it looks like we may have to use RULE and expressions to accommodate our needs and when we use expressions, the cell evaluation fails with some exception.  Appears to me as missing some basic step in setting up nCube in our setup. 

Here are the steps we followed:
1. Reused the JSON from your test resources (RuleswithDefault.json)
2. Loaded JSON Using  _NCube.fromSimpleJson(stream);_
3.  Used groovy to have the below test to run
                _coord.state = 'OH'
		coord.age = 18
		ncube.getCell coord, output_

A guide/examples to setup application to use with RULES/Expressions will be great..
I am getting the below exception, 

> 
> _Caused by: com.cedarsoftware.ncube.exception.CommandCellException: Error occurred in cube: Rules_with_Default2
> 
> 	at com.cedarsoftware.ncube.NCube.executeExpression(NCube.groovy:763) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.NCube.getCell(NCube.groovy:661) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.NCube.getCell(NCube.groovy) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.NCube$getCell.call(Unknown Source) ~[na:na]
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-all-2.4.15.jar:2.4.15]
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-all-2.4.15.jar:2.4.15]
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136) ~[groovy-all-2.4.15.jar:2.4.15]
> 	at com.vzw.test.Test.applyTestRule(Test.groovy:21) ~[main/:na]
> 	... 18 common frames omitted
> Caused by: java.lang.NullPointerException: null
> 	at com.cedarsoftware.ncube.NCubeAppContext.getBean(NCubeAppContext.groovy:36) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.NCubeAppContext.getNcubeRuntime(NCubeAppContext.groovy:52) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.GroovyExpression.buildGroovy(GroovyExpression.groovy:89) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.GroovyBase.computeL2CacheKey(GroovyBase.groovy:528) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.GroovyBase.prepare(GroovyBase.groovy:166) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.GroovyBase.fetchResult(GroovyBase.groovy:98) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.UrlCommandCell.execute(UrlCommandCell.groovy:227) ~[n-cube-4.4.1.jar:4.4.1]
> 	at com.cedarsoftware.ncube.NCube.executeExpression(NCube.groovy:740) ~[n-cube-4.4.1.jar:4.4.1]
> 	... 38 common frames omitted_
>

**Comment by jdereg** [comment]
Is your application using the Spring framework?

**Comment by PulThom** [comment]
Yes. It is using spring framework.
